# Generated by Django 4.1.3 on 2023-02-02 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ('-posted_at',)},
        ),
        migrations.AddField(
            model_name='deleterequest',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookstore.book'),
            preserve_default=False,
        ),
    ]
